### ISSUE TITLE
SQLiteException: near "WITHOUT"

### ISSUE THREAD

**Issue by pbelokopytov** [webim/webim-android-sdk-demo#2]
version Android: 4.4.4
version webimclientsdkandroid: 3.23.0

android.database.sqlite.SQLiteException: near "WITHOUT": syntax error (code 1): , while compiling: CREATE TABLE history
    (
        msg_id VARCHAR(64) PRIMARY KEY NOT NULL,
        client_side_id VARCHAR(64),
        ts BIGINT NOT NULL,
        sender_id VARCHAR(64),
        sender_name VARCHAR(255) NOT NULL,
        avatar VARCHAR(255),
        type TINYINT NOT NULL,
        text TEXT NOT NULL,
        data TEXT
    ) WITHOUT ROWID; CREATE UNIQUE INDEX history_ts ON history (ts)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1113)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:690)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1793)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1724)
        at com.webimapp.android.sdk.impl.SQLiteHistoryStorage$MyDBHelper.onCreate(SQLiteHistoryStorage.java:443)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
        at com.webimapp.android.sdk.impl.SQLiteHistoryStorage.prepare(SQLiteHistoryStorage.java:81)
        at com.webimapp.android.sdk.impl.SQLiteHistoryStorage.access$000(SQLiteHistoryStorage.java:28)
        at com.webimapp.android.sdk.impl.SQLiteHistoryStorage$1.run(SQLiteHistoryStorage.java:109)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

**Comment by webim** [comment]
Fixed since 3.23.1.
